id: P000575
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:47:51.060917
source_metadata:
  id: bdr:W1KG4467
  title: སོ་སོར་ཐར་པའི་མདོ
  author: ''
  volumes:
    d3fcd8be22a2498282b71ad9fe2b0e3f:
      image_group_id: I1KG4489
      title: Volume 1 of so sor thar pa'i mdo
      volume_number: 1
      total_pages: 110
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
